version: 1.1.0

modifiers:
    - !GMPruningModifier
        end_epoch: 171.0
        final_sparsity: 0.43
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['_model.encoders.1.basic_module.conv2.conv.weight', '_model.encoders.1.basic_module.conv3.conv.weight', '_model.encoders.2.basic_module.conv1.conv.weight', '_model.decoders.1.basic_module.conv1.conv.weight', '_model.decoders.1.basic_module.conv2.conv.weight', '_model.decoders.1.basic_module.conv3.conv.weight']
        phased: False
        score_type: magnitude
        start_epoch: 1.0
        update_frequency: 4.25

    - !GMPruningModifier
        end_epoch: 171.0
        final_sparsity: 0.86
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['_model.encoders.3.basic_module.conv2.conv.weight', '_model.encoders.3.basic_module.conv3.conv.weight']
        phased: False
        score_type: magnitude
        start_epoch: 1.0
        update_frequency: 4.25

    - !GMPruningModifier
        end_epoch: 171.0
        final_sparsity: 0.61
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['_model.encoders.2.basic_module.conv2.conv.weight', '_model.encoders.2.basic_module.conv3.conv.weight', '_model.encoders.3.basic_module.conv1.conv.weight', '_model.decoders.0.basic_module.conv1.conv.weight', '_model.decoders.0.basic_module.conv2.conv.weight', '_model.decoders.0.basic_module.conv3.conv.weight']
        phased: False
        score_type: magnitude
        start_epoch: 1.0
        update_frequency: 4.25

    - !EpochRangeModifier
        end_epoch: 299.0
        start_epoch: 0.0

    - !SetLearningRateModifier
        constant_logging: False
        end_epoch: -1
        learning_rate: 0.00055
        log_types: __ALL__
        start_epoch: 0.0

    - !LearningRateModifier
        constant_logging: False
        end_epoch: -1.0
        init_lr: 0.0001375
        log_types: __ALL__
        lr_class: StepLR
        lr_kwargs: {'gamma': 0.25, 'step_size': 67}
        start_epoch: 171.0
        update_frequency: -1.0
